name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        # install_url: https://github.com/nixos/nixpkgs/archive/bc260badaebf67442befe20fb443034d3a91f2b3.tar.gz
    - run: nix-build release.nix
